@startuml
|客户|
start
    #98FB98:申请服务;
|业务经理|
if(是新客户吗) then(是)
    :登记客户信息;
else(不是)
endif
    :上门勘察;
    :制定方案;
|客户|
if(满意吗) then(否)
    end
else(是)
    #98FB98:签订服务合同;
endif
|业务经理|
fork
    :安排工人;
fork again
    :安排材料;
end fork
    :填写派工单;
|工人|
    #8DB6CD:领取材料;
    #8DB6CD:上门服务;
|客户|
    #98FB98:验收并填写反馈意见;
|业务经理|
    :交回派工单;
|财务人员|
    #EEEE00:结算收款;
end

@enduml