@startuml

left to right direction
:系统管理员: as SysAdmin
:图书管理员: as Admin
:借阅者: as User


rectangle 图书管理系统{
User --> (登录)
User --> (查询借阅情况)
User --> (预约图书)
(预约图书).>(登录):<<include>>
User --> (续借图书)
User --> (查询书目)
User --> (借书卡挂失)

(借出图书).>(验证读者身份信息):<<include>>
(借出图书) <-  Admin
(验证读者身份信息)<.(归还图书):<<include>>
(归还图书)<.(超期罚款):<<extend>>
(归还图书) <- Admin
(登录)<--- Admin

(读者信息维护) <- SysAdmin
(借书卡管理).>(借书卡补办):<<extends>>
(借书卡管理) <- SysAdmin
(借书卡挂失)<.(借书卡管理):<<extends>>
(书目维护) <--- SysAdmin
(书目维护).>(删除书目):<<extends>>
(修改书目)<.(书目维护):<<extends>>
(添加书目)<.(书目维护):<<extends>>
(查询书目)<.(书目维护):<<use>>
}

@enduml